spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: local
    url: jdbc:mysql://localhost:3306/test
    password: xxxxxxx
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: 'true'







